import type { Job } from "@/lib/types";

export const DEMO_JOBS: Job[] = [
  {
    id: "demo-job-1",
    slug: "tbs-yoru-kai-ad",
    created_at: "2026-06-24T07:38:40+00:00",
    title: "TBS「櫻井・有吉 THE夜会」AD募集（未経験OK）",
    category: "制作・AD",
    job_type: "中長期案件",
    body: "人気バラエティ番組のAD（アシスタントディレクター）を募集します。\n未経験OK。先輩スタッフがしっかりサポートします。",
    location: "東京都",
    pay: "月給22万円〜（経験・能力により優遇）",
    pay_type: "月給",
    wage_min: null,
    work_period: "中長期（社員・契約）",
    headcount: 2,
    deadline: null,
    tags: ["未経験歓迎", "AD", "制作", "バラエティ"],
    is_active: true,
  },
  {
    id: "demo-job-2",
    slug: "ntv-lavit-ad",
    created_at: "2026-06-24T07:38:40+00:00",
    title: "NTV「サクサクヒムヒム」・TBS「ラヴィット！」AD募集（未経験OK）",
    category: "制作・AD",
    job_type: "中長期案件",
    body: "朝の情報・バラエティ番組のAD（アシスタントディレクター）を募集します。\n未経験OK。エンタメ業界デビューを応援します。",
    location: "東京都",
    pay: "月給22万円〜（経験・能力により優遇）",
    pay_type: "月給",
    wage_min: null,
    work_period: "中長期（社員・契約）",
    headcount: 2,
    deadline: null,
    tags: ["未経験歓迎", "AD", "制作", "朝番組", "バラエティ"],
    is_active: true,
  },
];
